name: Zip Mod Content
on:
  push:
    paths:
    - 'Mod/*'
  workflow_dispatch:
jobs:
  zipcontent:
    name: Zip Mod Content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          # Filename for archive
          filename: ModArchive.zip # default is release.zip
          # Working directory before zipping
          directory: . # optional, default is .
          # Base path for archive files
          path: Mod # optional, default is .
          artifacts: ModArchive.zip
